import { useAuth } from "@/lib/auth";
import { useClientContext } from "@/context/ClientContext";
import { RecommendationList } from "@/components/recommendations/RecommendationList";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Lightbulb } from "lucide-react";

export default function Recommendations() {
  const { user } = useAuth();
  const { viewingClientId, viewingClientName } = useClientContext();
  
  // For therapists viewing client's recommendations
  const userId = viewingClientId || user?.id || 0;
  const isTherapist = user?.role === "therapist" && viewingClientId !== null;
  
  // For admin users, we'll show both views
  const isAdmin = user?.role === "admin";
  
  return (
    <div className="container mx-auto py-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">AI Recommendations</h1>
          <p className="text-muted-foreground">
            {isTherapist 
              ? `View and approve personalized recommendations for ${viewingClientName}`
              : "Personalized suggestions based on your therapy journey"}
          </p>
        </div>
      </div>
      
      {(isTherapist || isAdmin) ? (
        <Tabs defaultValue="pending" className="w-full">
          <TabsList>
            <TabsTrigger value="pending">Pending Review</TabsTrigger>
            <TabsTrigger value="all">All Recommendations</TabsTrigger>
          </TabsList>
          
          <TabsContent value="pending" className="mt-4">
            <RecommendationList 
              userId={userId} 
              isTherapistView={true}
              pendingOnly={true}
            />
          </TabsContent>
          
          <TabsContent value="all" className="mt-4">
            <RecommendationList 
              userId={userId} 
              isTherapistView={true}
              pendingOnly={false}
            />
          </TabsContent>
        </Tabs>
      ) : (
        <>
          <InfoCard />
          <RecommendationList userId={userId} />
        </>
      )}
    </div>
  );
}

function InfoCard() {
  return (
    <Card className="mb-6 bg-gradient-to-br from-blue-50 to-indigo-50 border-blue-100">
      <CardHeader className="pb-2">
        <div className="flex items-center gap-2">
          <Lightbulb className="h-5 w-5 text-blue-500" />
          <CardTitle className="text-lg text-blue-700">About AI Recommendations</CardTitle>
        </div>
        <CardDescription className="text-blue-700/70">
          Personalized suggestions to support your mental health journey
        </CardDescription>
      </CardHeader>
      <CardContent className="text-sm text-blue-700/90">
        <p>
          These recommendations are generated by analyzing patterns in your activities, emotions, 
          and progress. Each suggestion has been carefully reviewed by your therapist to ensure 
          it's appropriate for your specific needs.
        </p>
      </CardContent>
    </Card>
  );
}